/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const TextContent = IDL.Record({
  'spanish' : IDL.Text,
  'english' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const BlockType = IDL.Variant({
  'textBlock' : IDL.Null,
  'imageBlock' : IDL.Null,
  'mixedBlock' : IDL.Null,
});
export const Time = IDL.Int;
export const ContentBlock = IDL.Record({
  'id' : IDL.Nat,
  'title' : TextContent,
  'content' : TextContent,
  'order' : IDL.Nat,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'blockType' : BlockType,
  'isVisible' : IDL.Bool,
  'image' : IDL.Opt(ExternalBlob),
});
export const HowToOrderStep = IDL.Record({
  'title' : TextContent,
  'description' : TextContent,
  'stepNumber' : IDL.Nat,
  'image' : IDL.Opt(ExternalBlob),
});
export const Package = IDL.Record({
  'id' : IDL.Text,
  'name' : TextContent,
  'description' : TextContent,
  'image' : ExternalBlob,
  'price' : TextContent,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'title' : TextContent,
  'description' : TextContent,
  'image' : ExternalBlob,
  'price' : TextContent,
});
export const SocialMediaLink = IDL.Record({
  'url' : IDL.Text,
  'icon' : IDL.Opt(ExternalBlob),
  'platform' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdminUser = IDL.Record({
  'username' : IDL.Text,
  'password' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Text,
  'fullName' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const SectionContentView = IDL.Record({
  'id' : IDL.Text,
  'title' : TextContent,
  'background' : IDL.Opt(ExternalBlob),
  'order' : IDL.Nat,
  'createdBy' : IDL.Principal,
  'lastUpdated' : Time,
  'description' : TextContent,
  'contentBlocks' : IDL.Vec(ContentBlock),
  'isVisible' : IDL.Bool,
  'image' : IDL.Opt(ExternalBlob),
});
export const ContentBlockView = IDL.Record({
  'id' : IDL.Nat,
  'title' : TextContent,
  'content' : TextContent,
  'order' : IDL.Nat,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'blockType' : BlockType,
  'isVisible' : IDL.Bool,
  'image' : IDL.Opt(ExternalBlob),
});
export const Language = IDL.Variant({
  'spanish' : IDL.Null,
  'english' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'language' : Language,
});
export const InstagramFeedConfig = IDL.Record({
  'title' : TextContent,
  'displayOrder' : IDL.Nat,
  'createdBy' : IDL.Text,
  'instagramHandle' : IDL.Text,
  'lastUpdated' : Time,
  'description' : TextContent,
  'isVisible' : IDL.Bool,
  'instagramEmbedCode' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addContentBlock' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        TextContent,
        TextContent,
        IDL.Opt(ExternalBlob),
        BlockType,
        IDL.Nat,
        IDL.Bool,
      ],
      [ContentBlock],
      [],
    ),
  'addHowToOrderStep' : IDL.Func(
      [IDL.Text, IDL.Nat, TextContent, TextContent, IDL.Opt(ExternalBlob)],
      [HowToOrderStep],
      [],
    ),
  'addPackage' : IDL.Func(
      [IDL.Text, TextContent, TextContent, ExternalBlob, TextContent],
      [Package],
      [],
    ),
  'addProduct' : IDL.Func(
      [IDL.Text, TextContent, TextContent, ExternalBlob, TextContent],
      [Product],
      [],
    ),
  'addSocialMediaLink' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [SocialMediaLink],
      [],
    ),
  'adminDeleteContentBlock' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'adminLogout' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAdditionalSection' : IDL.Func(
      [
        IDL.Text,
        TextContent,
        TextContent,
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
        IDL.Nat,
        IDL.Bool,
      ],
      [IDL.Text],
      [],
    ),
  'createAdminUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'deleteAdditionalSection' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deletePackage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteSocialMediaLink' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'editHowToOrderStep' : IDL.Func(
      [IDL.Text, IDL.Nat, TextContent, TextContent, IDL.Opt(ExternalBlob)],
      [HowToOrderStep],
      [],
    ),
  'editPackage' : IDL.Func(
      [IDL.Text, IDL.Text, TextContent, TextContent, ExternalBlob, TextContent],
      [Package],
      [],
    ),
  'editProduct' : IDL.Func(
      [IDL.Text, IDL.Text, TextContent, TextContent, ExternalBlob, TextContent],
      [Product],
      [],
    ),
  'editSocialMediaLink' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [SocialMediaLink],
      [],
    ),
  'getAdminUsers' : IDL.Func([IDL.Text], [IDL.Vec(AdminUser)], ['query']),
  'getAllAdditionalSections' : IDL.Func(
      [],
      [IDL.Vec(SectionContentView)],
      ['query'],
    ),
  'getAllContentBlocksAdmin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(ContentBlockView)],
      ['query'],
    ),
  'getAllHowToOrderSteps' : IDL.Func([], [IDL.Vec(HowToOrderStep)], ['query']),
  'getAllPackageIds' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllSectionsAdmin' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SectionContentView)],
      ['query'],
    ),
  'getAllSocialMediaLinks' : IDL.Func(
      [],
      [IDL.Vec(SocialMediaLink)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInstagramFeedConfig' : IDL.Func(
      [],
      [IDL.Opt(InstagramFeedConfig)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisibleContentBlockAdmin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(ContentBlockView)],
      ['query'],
    ),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAdditionalSection' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        TextContent,
        TextContent,
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
        IDL.Nat,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateInstagramFeedConfig' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        TextContent,
        TextContent,
        IDL.Nat,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'validateSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const TextContent = IDL.Record({
    'spanish' : IDL.Text,
    'english' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const BlockType = IDL.Variant({
    'textBlock' : IDL.Null,
    'imageBlock' : IDL.Null,
    'mixedBlock' : IDL.Null,
  });
  const Time = IDL.Int;
  const ContentBlock = IDL.Record({
    'id' : IDL.Nat,
    'title' : TextContent,
    'content' : TextContent,
    'order' : IDL.Nat,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'blockType' : BlockType,
    'isVisible' : IDL.Bool,
    'image' : IDL.Opt(ExternalBlob),
  });
  const HowToOrderStep = IDL.Record({
    'title' : TextContent,
    'description' : TextContent,
    'stepNumber' : IDL.Nat,
    'image' : IDL.Opt(ExternalBlob),
  });
  const Package = IDL.Record({
    'id' : IDL.Text,
    'name' : TextContent,
    'description' : TextContent,
    'image' : ExternalBlob,
    'price' : TextContent,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'title' : TextContent,
    'description' : TextContent,
    'image' : ExternalBlob,
    'price' : TextContent,
  });
  const SocialMediaLink = IDL.Record({
    'url' : IDL.Text,
    'icon' : IDL.Opt(ExternalBlob),
    'platform' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdminUser = IDL.Record({
    'username' : IDL.Text,
    'password' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Text,
    'fullName' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const SectionContentView = IDL.Record({
    'id' : IDL.Text,
    'title' : TextContent,
    'background' : IDL.Opt(ExternalBlob),
    'order' : IDL.Nat,
    'createdBy' : IDL.Principal,
    'lastUpdated' : Time,
    'description' : TextContent,
    'contentBlocks' : IDL.Vec(ContentBlock),
    'isVisible' : IDL.Bool,
    'image' : IDL.Opt(ExternalBlob),
  });
  const ContentBlockView = IDL.Record({
    'id' : IDL.Nat,
    'title' : TextContent,
    'content' : TextContent,
    'order' : IDL.Nat,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'blockType' : BlockType,
    'isVisible' : IDL.Bool,
    'image' : IDL.Opt(ExternalBlob),
  });
  const Language = IDL.Variant({ 'spanish' : IDL.Null, 'english' : IDL.Null });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'language' : Language,
  });
  const InstagramFeedConfig = IDL.Record({
    'title' : TextContent,
    'displayOrder' : IDL.Nat,
    'createdBy' : IDL.Text,
    'instagramHandle' : IDL.Text,
    'lastUpdated' : Time,
    'description' : TextContent,
    'isVisible' : IDL.Bool,
    'instagramEmbedCode' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addContentBlock' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          TextContent,
          TextContent,
          IDL.Opt(ExternalBlob),
          BlockType,
          IDL.Nat,
          IDL.Bool,
        ],
        [ContentBlock],
        [],
      ),
    'addHowToOrderStep' : IDL.Func(
        [IDL.Text, IDL.Nat, TextContent, TextContent, IDL.Opt(ExternalBlob)],
        [HowToOrderStep],
        [],
      ),
    'addPackage' : IDL.Func(
        [IDL.Text, TextContent, TextContent, ExternalBlob, TextContent],
        [Package],
        [],
      ),
    'addProduct' : IDL.Func(
        [IDL.Text, TextContent, TextContent, ExternalBlob, TextContent],
        [Product],
        [],
      ),
    'addSocialMediaLink' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [SocialMediaLink],
        [],
      ),
    'adminDeleteContentBlock' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'adminLogout' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAdditionalSection' : IDL.Func(
        [
          IDL.Text,
          TextContent,
          TextContent,
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
          IDL.Nat,
          IDL.Bool,
        ],
        [IDL.Text],
        [],
      ),
    'createAdminUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'deleteAdditionalSection' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deletePackage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteSocialMediaLink' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'editHowToOrderStep' : IDL.Func(
        [IDL.Text, IDL.Nat, TextContent, TextContent, IDL.Opt(ExternalBlob)],
        [HowToOrderStep],
        [],
      ),
    'editPackage' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          TextContent,
          TextContent,
          ExternalBlob,
          TextContent,
        ],
        [Package],
        [],
      ),
    'editProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          TextContent,
          TextContent,
          ExternalBlob,
          TextContent,
        ],
        [Product],
        [],
      ),
    'editSocialMediaLink' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [SocialMediaLink],
        [],
      ),
    'getAdminUsers' : IDL.Func([IDL.Text], [IDL.Vec(AdminUser)], ['query']),
    'getAllAdditionalSections' : IDL.Func(
        [],
        [IDL.Vec(SectionContentView)],
        ['query'],
      ),
    'getAllContentBlocksAdmin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(ContentBlockView)],
        ['query'],
      ),
    'getAllHowToOrderSteps' : IDL.Func(
        [],
        [IDL.Vec(HowToOrderStep)],
        ['query'],
      ),
    'getAllPackageIds' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllSectionsAdmin' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SectionContentView)],
        ['query'],
      ),
    'getAllSocialMediaLinks' : IDL.Func(
        [],
        [IDL.Vec(SocialMediaLink)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInstagramFeedConfig' : IDL.Func(
        [],
        [IDL.Opt(InstagramFeedConfig)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisibleContentBlockAdmin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(ContentBlockView)],
        ['query'],
      ),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAdditionalSection' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          TextContent,
          TextContent,
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
          IDL.Nat,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateInstagramFeedConfig' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          TextContent,
          TextContent,
          IDL.Nat,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'validateSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };