/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BlockType = { 'textBlock' : null } |
  { 'imageBlock' : null } |
  { 'mixedBlock' : null };
export interface ContentBlock {
  'id' : bigint,
  'title' : TextContent,
  'content' : TextContent,
  'order' : bigint,
  'createdAt' : Time,
  'createdBy' : Principal,
  'blockType' : BlockType,
  'isVisible' : boolean,
  'image' : [] | [ExternalBlob],
}
export interface ContentBlockView {
  'id' : bigint,
  'title' : TextContent,
  'content' : TextContent,
  'order' : bigint,
  'createdAt' : Time,
  'createdBy' : Principal,
  'blockType' : BlockType,
  'isVisible' : boolean,
  'image' : [] | [ExternalBlob],
}
export type ExternalBlob = Uint8Array;
export interface HowToOrderStep {
  'title' : TextContent,
  'description' : TextContent,
  'stepNumber' : bigint,
  'image' : [] | [ExternalBlob],
}
export interface InstagramFeedConfig {
  'title' : TextContent,
  'displayOrder' : bigint,
  'createdBy' : string,
  'instagramHandle' : string,
  'lastUpdated' : Time,
  'description' : TextContent,
  'isVisible' : boolean,
  'instagramEmbedCode' : string,
}
export type Language = { 'spanish' : null } |
  { 'english' : null };
export interface Package {
  'id' : string,
  'name' : TextContent,
  'description' : TextContent,
  'image' : ExternalBlob,
  'price' : TextContent,
}
export interface Product {
  'id' : string,
  'title' : TextContent,
  'description' : TextContent,
  'image' : ExternalBlob,
  'price' : TextContent,
}
export interface SectionContentView {
  'id' : string,
  'title' : TextContent,
  'background' : [] | [ExternalBlob],
  'order' : bigint,
  'createdBy' : Principal,
  'lastUpdated' : Time,
  'description' : TextContent,
  'contentBlocks' : Array<ContentBlock>,
  'isVisible' : boolean,
  'image' : [] | [ExternalBlob],
}
export interface SocialMediaLink {
  'url' : string,
  'icon' : [] | [ExternalBlob],
  'platform' : string,
}
export interface TextContent { 'spanish' : string, 'english' : string }
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'language' : Language,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addContentBlock' : ActorMethod<
    [
      string,
      TextContent,
      TextContent,
      [] | [ExternalBlob],
      BlockType,
      bigint,
      boolean,
    ],
    ContentBlock
  >,
  'addHowToOrderStep' : ActorMethod<
    [bigint, TextContent, TextContent, [] | [ExternalBlob]],
    HowToOrderStep
  >,
  'addPackage' : ActorMethod<
    [TextContent, TextContent, ExternalBlob, TextContent],
    Package
  >,
  'addProduct' : ActorMethod<
    [TextContent, TextContent, ExternalBlob, TextContent],
    Product
  >,
  'addSocialMediaLink' : ActorMethod<
    [string, string, [] | [ExternalBlob]],
    SocialMediaLink
  >,
  'adminDeleteContentBlock' : ActorMethod<[string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bootstrapAdmin' : ActorMethod<[], undefined>,
  'createAdditionalSection' : ActorMethod<
    [
      TextContent,
      TextContent,
      [] | [ExternalBlob],
      [] | [ExternalBlob],
      bigint,
      boolean,
    ],
    string
  >,
  'deleteAdditionalSection' : ActorMethod<[string], undefined>,
  'deletePackage' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'deleteSocialMediaLink' : ActorMethod<[string], undefined>,
  'editHowToOrderStep' : ActorMethod<
    [bigint, TextContent, TextContent, [] | [ExternalBlob]],
    HowToOrderStep
  >,
  'editPackage' : ActorMethod<
    [string, TextContent, TextContent, ExternalBlob, TextContent],
    Package
  >,
  'editProduct' : ActorMethod<
    [string, TextContent, TextContent, ExternalBlob, TextContent],
    Product
  >,
  'editSocialMediaLink' : ActorMethod<
    [string, string, [] | [ExternalBlob]],
    SocialMediaLink
  >,
  'getAllAdditionalSections' : ActorMethod<[], Array<SectionContentView>>,
  'getAllContentBlocksAdmin' : ActorMethod<[string], Array<ContentBlockView>>,
  'getAllHowToOrderSteps' : ActorMethod<[], Array<HowToOrderStep>>,
  'getAllPackageIds' : ActorMethod<[], Array<string>>,
  'getAllPackages' : ActorMethod<[], Array<Package>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllSectionsAdmin' : ActorMethod<[], Array<SectionContentView>>,
  'getAllSocialMediaLinks' : ActorMethod<[], Array<SocialMediaLink>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInstagramFeedConfig' : ActorMethod<[], [] | [InstagramFeedConfig]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisibleContentBlockAdmin' : ActorMethod<
    [string],
    Array<ContentBlockView>
  >,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAdditionalSection' : ActorMethod<
    [
      string,
      TextContent,
      TextContent,
      [] | [ExternalBlob],
      [] | [ExternalBlob],
      bigint,
      boolean,
    ],
    undefined
  >,
  'updateInstagramFeedConfig' : ActorMethod<
    [string, string, TextContent, TextContent, bigint, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];