/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface TextContent {
    spanish: string;
    english: string;
}
export interface ContentBlock {
    id: bigint;
    title: TextContent;
    content: TextContent;
    order: bigint;
    createdAt: Time;
    createdBy: Principal;
    blockType: BlockType;
    isVisible: boolean;
    image?: ExternalBlob;
}
export type Time = bigint;
export interface AdminUser {
    username: string;
    password: string;
    createdAt: Time;
    createdBy: string;
    fullName: string;
    isActive: boolean;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface SectionContentView {
    id: string;
    title: TextContent;
    background?: ExternalBlob;
    order: bigint;
    createdBy: Principal;
    lastUpdated: Time;
    description: TextContent;
    contentBlocks: Array<ContentBlock>;
    isVisible: boolean;
    image?: ExternalBlob;
}
export interface SocialMediaLink {
    url: string;
    icon?: ExternalBlob;
    platform: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Package {
    id: string;
    name: TextContent;
    description: TextContent;
    image: ExternalBlob;
    price: TextContent;
}
export interface ContentBlockView {
    id: bigint;
    title: TextContent;
    content: TextContent;
    order: bigint;
    createdAt: Time;
    createdBy: Principal;
    blockType: BlockType;
    isVisible: boolean;
    image?: ExternalBlob;
}
export interface HowToOrderStep {
    title: TextContent;
    description: TextContent;
    stepNumber: bigint;
    image?: ExternalBlob;
}
export interface InstagramFeedConfig {
    title: TextContent;
    displayOrder: bigint;
    createdBy: string;
    instagramHandle: string;
    lastUpdated: Time;
    description: TextContent;
    isVisible: boolean;
    instagramEmbedCode: string;
}
export interface Product {
    id: string;
    title: TextContent;
    description: TextContent;
    image: ExternalBlob;
    price: TextContent;
}
export interface UserProfile {
    name: string;
    email?: string;
    language: Language;
}
export enum BlockType {
    textBlock = "textBlock",
    imageBlock = "imageBlock",
    mixedBlock = "mixedBlock"
}
export enum Language {
    spanish = "spanish",
    english = "english"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addContentBlock(sessionId: string, sectionId: string, title: TextContent, content: TextContent, image: ExternalBlob | null, blockType: BlockType, order: bigint, isVisible: boolean): Promise<ContentBlock>;
    addHowToOrderStep(sessionId: string, stepNumber: bigint, title: TextContent, description: TextContent, image: ExternalBlob | null): Promise<HowToOrderStep>;
    addPackage(sessionId: string, name: TextContent, description: TextContent, image: ExternalBlob, price: TextContent): Promise<Package>;
    addProduct(sessionId: string, title: TextContent, description: TextContent, image: ExternalBlob, price: TextContent): Promise<Product>;
    addSocialMediaLink(sessionId: string, platform: string, url: string, icon: ExternalBlob | null): Promise<SocialMediaLink>;
    adminDeleteContentBlock(sessionId: string, sectionId: string, blockId: bigint): Promise<void>;
    adminLogin(username: string, password: string): Promise<string>;
    adminLogout(sessionId: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAdditionalSection(sessionId: string, title: TextContent, description: TextContent, image: ExternalBlob | null, background: ExternalBlob | null, order: bigint, isVisible: boolean): Promise<string>;
    createAdminUser(sessionId: string, username: string, fullName: string, password: string): Promise<void>;
    deleteAdditionalSection(sessionId: string, id: string): Promise<void>;
    deletePackage(sessionId: string, id: string): Promise<void>;
    deleteProduct(sessionId: string, id: string): Promise<void>;
    deleteSocialMediaLink(sessionId: string, platform: string): Promise<void>;
    editHowToOrderStep(sessionId: string, stepNumber: bigint, title: TextContent, description: TextContent, image: ExternalBlob | null): Promise<HowToOrderStep>;
    editPackage(sessionId: string, id: string, name: TextContent, description: TextContent, image: ExternalBlob, price: TextContent): Promise<Package>;
    editProduct(sessionId: string, id: string, title: TextContent, description: TextContent, image: ExternalBlob, price: TextContent): Promise<Product>;
    editSocialMediaLink(sessionId: string, platform: string, url: string, icon: ExternalBlob | null): Promise<SocialMediaLink>;
    getAdminUsers(sessionId: string): Promise<Array<AdminUser>>;
    getAllAdditionalSections(): Promise<Array<SectionContentView>>;
    getAllContentBlocksAdmin(sessionId: string, sectionId: string): Promise<Array<ContentBlockView>>;
    getAllHowToOrderSteps(): Promise<Array<HowToOrderStep>>;
    getAllPackageIds(): Promise<Array<string>>;
    getAllPackages(): Promise<Array<Package>>;
    getAllProducts(): Promise<Array<Product>>;
    getAllSectionsAdmin(sessionId: string): Promise<Array<SectionContentView>>;
    getAllSocialMediaLinks(): Promise<Array<SocialMediaLink>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getInstagramFeedConfig(): Promise<InstagramFeedConfig | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVisibleContentBlockAdmin(sessionId: string, sectionId: string): Promise<Array<ContentBlockView>>;
    isAdmin(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateAdditionalSection(sessionId: string, id: string, title: TextContent, description: TextContent, image: ExternalBlob | null, background: ExternalBlob | null, order: bigint, isVisible: boolean): Promise<void>;
    updateInstagramFeedConfig(sessionId: string, instagramHandle: string, instagramEmbedCode: string, title: TextContent, description: TextContent, displayOrder: bigint, isVisible: boolean): Promise<void>;
    validateSession(sessionId: string): Promise<boolean>;
}
import type { BlockType as _BlockType, ContentBlock as _ContentBlock, ContentBlockView as _ContentBlockView, ExternalBlob as _ExternalBlob, HowToOrderStep as _HowToOrderStep, InstagramFeedConfig as _InstagramFeedConfig, Language as _Language, Package as _Package, Product as _Product, SectionContentView as _SectionContentView, SocialMediaLink as _SocialMediaLink, TextContent as _TextContent, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addContentBlock(arg0: string, arg1: string, arg2: TextContent, arg3: TextContent, arg4: ExternalBlob | null, arg5: BlockType, arg6: bigint, arg7: boolean): Promise<ContentBlock> {
        if (this.processError) {
            try {
                const result = await this.actor.addContentBlock(arg0, arg1, arg2, arg3, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), to_candid_BlockType_n10(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
                return from_candid_ContentBlock_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContentBlock(arg0, arg1, arg2, arg3, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), to_candid_BlockType_n10(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
            return from_candid_ContentBlock_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async addHowToOrderStep(arg0: string, arg1: bigint, arg2: TextContent, arg3: TextContent, arg4: ExternalBlob | null): Promise<HowToOrderStep> {
        if (this.processError) {
            try {
                const result = await this.actor.addHowToOrderStep(arg0, arg1, arg2, arg3, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4));
                return from_candid_HowToOrderStep_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHowToOrderStep(arg0, arg1, arg2, arg3, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4));
            return from_candid_HowToOrderStep_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async addPackage(arg0: string, arg1: TextContent, arg2: TextContent, arg3: ExternalBlob, arg4: TextContent): Promise<Package> {
        if (this.processError) {
            try {
                const result = await this.actor.addPackage(arg0, arg1, arg2, await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_Package_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPackage(arg0, arg1, arg2, await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_Package_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async addProduct(arg0: string, arg1: TextContent, arg2: TextContent, arg3: ExternalBlob, arg4: TextContent): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, arg1, arg2, await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_Product_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, arg1, arg2, await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_Product_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async addSocialMediaLink(arg0: string, arg1: string, arg2: string, arg3: ExternalBlob | null): Promise<SocialMediaLink> {
        if (this.processError) {
            try {
                const result = await this.actor.addSocialMediaLink(arg0, arg1, arg2, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3));
                return from_candid_SocialMediaLink_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSocialMediaLink(arg0, arg1, arg2, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3));
            return from_candid_SocialMediaLink_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminDeleteContentBlock(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteContentBlock(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteContentBlock(arg0, arg1, arg2);
            return result;
        }
    }
    async adminLogin(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return result;
        }
    }
    async adminLogout(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogout(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n26(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n26(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAdditionalSection(arg0: string, arg1: TextContent, arg2: TextContent, arg3: ExternalBlob | null, arg4: ExternalBlob | null, arg5: bigint, arg6: boolean): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createAdditionalSection(arg0, arg1, arg2, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAdditionalSection(arg0, arg1, arg2, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
            return result;
        }
    }
    async createAdminUser(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAdminUser(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAdminUser(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteAdditionalSection(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAdditionalSection(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAdditionalSection(arg0, arg1);
            return result;
        }
    }
    async deletePackage(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePackage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePackage(arg0, arg1);
            return result;
        }
    }
    async deleteProduct(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0, arg1);
            return result;
        }
    }
    async deleteSocialMediaLink(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSocialMediaLink(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSocialMediaLink(arg0, arg1);
            return result;
        }
    }
    async editHowToOrderStep(arg0: string, arg1: bigint, arg2: TextContent, arg3: TextContent, arg4: ExternalBlob | null): Promise<HowToOrderStep> {
        if (this.processError) {
            try {
                const result = await this.actor.editHowToOrderStep(arg0, arg1, arg2, arg3, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4));
                return from_candid_HowToOrderStep_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editHowToOrderStep(arg0, arg1, arg2, arg3, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4));
            return from_candid_HowToOrderStep_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async editPackage(arg0: string, arg1: string, arg2: TextContent, arg3: TextContent, arg4: ExternalBlob, arg5: TextContent): Promise<Package> {
        if (this.processError) {
            try {
                const result = await this.actor.editPackage(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg4), arg5);
                return from_candid_Package_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editPackage(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg4), arg5);
            return from_candid_Package_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async editProduct(arg0: string, arg1: string, arg2: TextContent, arg3: TextContent, arg4: ExternalBlob, arg5: TextContent): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.editProduct(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg4), arg5);
                return from_candid_Product_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editProduct(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg4), arg5);
            return from_candid_Product_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async editSocialMediaLink(arg0: string, arg1: string, arg2: string, arg3: ExternalBlob | null): Promise<SocialMediaLink> {
        if (this.processError) {
            try {
                const result = await this.actor.editSocialMediaLink(arg0, arg1, arg2, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3));
                return from_candid_SocialMediaLink_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editSocialMediaLink(arg0, arg1, arg2, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3));
            return from_candid_SocialMediaLink_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminUsers(arg0: string): Promise<Array<AdminUser>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminUsers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminUsers(arg0);
            return result;
        }
    }
    async getAllAdditionalSections(): Promise<Array<SectionContentView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAdditionalSections();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAdditionalSections();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllContentBlocksAdmin(arg0: string, arg1: string): Promise<Array<ContentBlockView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContentBlocksAdmin(arg0, arg1);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContentBlocksAdmin(arg0, arg1);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllHowToOrderSteps(): Promise<Array<HowToOrderStep>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHowToOrderSteps();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHowToOrderSteps();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPackageIds(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPackageIds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPackageIds();
            return result;
        }
    }
    async getAllPackages(): Promise<Array<Package>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPackages();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPackages();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSectionsAdmin(arg0: string): Promise<Array<SectionContentView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSectionsAdmin(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSectionsAdmin(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSocialMediaLinks(): Promise<Array<SocialMediaLink>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSocialMediaLinks();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSocialMediaLinks();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInstagramFeedConfig(): Promise<InstagramFeedConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInstagramFeedConfig();
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInstagramFeedConfig();
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVisibleContentBlockAdmin(arg0: string, arg1: string): Promise<Array<ContentBlockView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisibleContentBlockAdmin(arg0, arg1);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisibleContentBlockAdmin(arg0, arg1);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n47(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n47(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateAdditionalSection(arg0: string, arg1: string, arg2: TextContent, arg3: TextContent, arg4: ExternalBlob | null, arg5: ExternalBlob | null, arg6: bigint, arg7: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdditionalSection(arg0, arg1, arg2, arg3, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdditionalSection(arg0, arg1, arg2, arg3, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
            return result;
        }
    }
    async updateInstagramFeedConfig(arg0: string, arg1: string, arg2: string, arg3: TextContent, arg4: TextContent, arg5: bigint, arg6: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInstagramFeedConfig(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInstagramFeedConfig(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async validateSession(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateSession(arg0);
            return result;
        }
    }
}
function from_candid_BlockType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlockType): BlockType {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
async function from_candid_ContentBlockView_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentBlockView): Promise<ContentBlockView> {
    return await from_candid_record_n13(_uploadFile, _downloadFile, value);
}
async function from_candid_ContentBlock_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentBlock): Promise<ContentBlock> {
    return await from_candid_record_n13(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_HowToOrderStep_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HowToOrderStep): Promise<HowToOrderStep> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Language_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Language): Language {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
async function from_candid_Package_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Package): Promise<Package> {
    return await from_candid_record_n21(_uploadFile, _downloadFile, value);
}
async function from_candid_Product_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Promise<Product> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_SectionContentView_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SectionContentView): Promise<SectionContentView> {
    return await from_candid_record_n30(_uploadFile, _downloadFile, value);
}
async function from_candid_SocialMediaLink_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SocialMediaLink): Promise<SocialMediaLink> {
    return await from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InstagramFeedConfig]): InstagramFeedConfig | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: _TextContent;
    content: _TextContent;
    order: bigint;
    createdAt: _Time;
    createdBy: Principal;
    blockType: _BlockType;
    isVisible: boolean;
    image: [] | [_ExternalBlob];
}): Promise<{
    id: bigint;
    title: TextContent;
    content: TextContent;
    order: bigint;
    createdAt: Time;
    createdBy: Principal;
    blockType: BlockType;
    isVisible: boolean;
    image?: ExternalBlob;
}> {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        order: value.order,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        blockType: from_candid_BlockType_n14(_uploadFile, _downloadFile, value.blockType),
        isVisible: value.isVisible,
        image: record_opt_to_undefined(await from_candid_opt_n16(_uploadFile, _downloadFile, value.image))
    };
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: _TextContent;
    description: _TextContent;
    stepNumber: bigint;
    image: [] | [_ExternalBlob];
}): Promise<{
    title: TextContent;
    description: TextContent;
    stepNumber: bigint;
    image?: ExternalBlob;
}> {
    return {
        title: value.title,
        description: value.description,
        stepNumber: value.stepNumber,
        image: record_opt_to_undefined(await from_candid_opt_n16(_uploadFile, _downloadFile, value.image))
    };
}
async function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: _TextContent;
    description: _TextContent;
    image: _ExternalBlob;
    price: _TextContent;
}): Promise<{
    id: string;
    name: TextContent;
    description: TextContent;
    image: ExternalBlob;
    price: TextContent;
}> {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        image: await from_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value.image),
        price: value.price
    };
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: _TextContent;
    description: _TextContent;
    image: _ExternalBlob;
    price: _TextContent;
}): Promise<{
    id: string;
    title: TextContent;
    description: TextContent;
    image: ExternalBlob;
    price: TextContent;
}> {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        image: await from_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value.image),
        price: value.price
    };
}
async function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    icon: [] | [_ExternalBlob];
    platform: string;
}): Promise<{
    url: string;
    icon?: ExternalBlob;
    platform: string;
}> {
    return {
        url: value.url,
        icon: record_opt_to_undefined(await from_candid_opt_n16(_uploadFile, _downloadFile, value.icon)),
        platform: value.platform
    };
}
async function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: _TextContent;
    background: [] | [_ExternalBlob];
    order: bigint;
    createdBy: Principal;
    lastUpdated: _Time;
    description: _TextContent;
    contentBlocks: Array<_ContentBlock>;
    isVisible: boolean;
    image: [] | [_ExternalBlob];
}): Promise<{
    id: string;
    title: TextContent;
    background?: ExternalBlob;
    order: bigint;
    createdBy: Principal;
    lastUpdated: Time;
    description: TextContent;
    contentBlocks: Array<ContentBlock>;
    isVisible: boolean;
    image?: ExternalBlob;
}> {
    return {
        id: value.id,
        title: value.title,
        background: record_opt_to_undefined(await from_candid_opt_n16(_uploadFile, _downloadFile, value.background)),
        order: value.order,
        createdBy: value.createdBy,
        lastUpdated: value.lastUpdated,
        description: value.description,
        contentBlocks: await from_candid_vec_n31(_uploadFile, _downloadFile, value.contentBlocks),
        isVisible: value.isVisible,
        image: record_opt_to_undefined(await from_candid_opt_n16(_uploadFile, _downloadFile, value.image))
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
    language: _Language;
}): {
    name: string;
    email?: string;
    language: Language;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.email)),
        language: from_candid_Language_n42(_uploadFile, _downloadFile, value.language)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    textBlock: null;
} | {
    imageBlock: null;
} | {
    mixedBlock: null;
}): BlockType {
    return "textBlock" in value ? BlockType.textBlock : "imageBlock" in value ? BlockType.imageBlock : "mixedBlock" in value ? BlockType.mixedBlock : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    spanish: null;
} | {
    english: null;
}): Language {
    return "spanish" in value ? Language.spanish : "english" in value ? Language.english : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SectionContentView>): Promise<Array<SectionContentView>> {
    return await Promise.all(value.map(async (x)=>await from_candid_SectionContentView_n29(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContentBlock>): Promise<Array<ContentBlock>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ContentBlock_n12(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContentBlockView>): Promise<Array<ContentBlockView>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ContentBlockView_n33(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HowToOrderStep>): Promise<Array<HowToOrderStep>> {
    return await Promise.all(value.map(async (x)=>await from_candid_HowToOrderStep_n18(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Package>): Promise<Array<Package>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Package_n20(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Promise<Array<Product>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Product_n22(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SocialMediaLink>): Promise<Array<SocialMediaLink>> {
    return await Promise.all(value.map(async (x)=>await from_candid_SocialMediaLink_n24(_uploadFile, _downloadFile, x)));
}
function to_candid_BlockType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlockType): _BlockType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Language_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): _Language {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n48(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n9(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
    language: Language;
}): {
    name: string;
    email: [] | [string];
    language: _Language;
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        language: to_candid_Language_n49(_uploadFile, _downloadFile, value.language)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlockType): {
    textBlock: null;
} | {
    imageBlock: null;
} | {
    mixedBlock: null;
} {
    return value == BlockType.textBlock ? {
        textBlock: null
    } : value == BlockType.imageBlock ? {
        imageBlock: null
    } : value == BlockType.mixedBlock ? {
        mixedBlock: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): {
    spanish: null;
} | {
    english: null;
} {
    return value == Language.spanish ? {
        spanish: null
    } : value == Language.english ? {
        english: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
